/**
 * 30_srp.test.mjs — PRIORITY 4: SRP-6a account authentication parity.
 *
 * Upstream authority:
 *   .upstream/pub/lib/srp/srp6_client.dart      (pointycastle 3.9.1)
 *   .upstream/pub/lib/srp/srp6_util.dart
 *   .upstream/pub/lib/srp/srp6_verifier_generator.dart
 *   .upstream/ente/mobile/packages/accounts/lib/services/user_service.dart
 *
 * THE VECTOR
 * ----------
 * Upstream ships no Ente-specific SRP vector in the Dart sources, but the Rust
 * client DOES: `.upstream/ente/rust/crates/accounts/src/auth/srp.rs:347-388`
 * carries `test_known_vector_leading_zero_a_matches_go_server_m1`, whose
 * expected M1 was "Generated by the Go server's github.com/ente/go-srp". That
 * gives a genuine THREE-WAY cross-implementation vector:
 *
 *   Go server (ente/go-srp)  ==  Rust client (srp crate)  ==  this port?
 *
 * It is also an edge case: `a` is tiny (0x6de), so A has a leading zero byte
 * and `assert_eq!(a_public.len(), SRP_N_BYTES - 1)` — the padding of A when
 * computing u is exactly what makes it pass.
 *
 * Inputs:
 *   srpUserID  = "repro-user-id"
 *   srpSalt    = "0123456789abcdef"   (16 ASCII bytes)
 *   loginKey   = "1234567890abcdef"   (16 ASCII bytes)
 *   a          = 0x06de               (64-byte big-endian private value)
 *   b          = 0x42 repeated 64x    (server private value)
 *   expected M1 = c0953b8c74d400fbf664a515deb700d73b65231e7e207a2e2326ff8cf70567ac
 */
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { assert, assertBytes, assertEquals, assertThrows, describe, hex, it } from '../framework.mjs';

const { Srp } = await import('../gen/entry/src/main/ets/account/Srp.ts');
const { CryptoUtil } = await import('../gen/entry/src/main/ets/crypto/CryptoUtil.ts');

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..', '..');

/**
 * The expected modulus is read straight out of the pinned upstream source, so
 * there is no hand-transcription to get wrong (the first pass DID get it wrong:
 * it shipped a 512-hex-char value that agreed with upstream for only the first
 * 491 characters).
 *
 * The full `.upstream/` reference checkout is not part of this repository, so a
 * verbatim pinned copy of this one file is vendored under
 * `tools/host-tests/upstream/srp/` (see that directory's README for provenance
 * and the sha256). A local `.upstream/` checkout, when present, takes priority.
 */
function upstreamRfc5054_4096_N() {
  const vendored = join(HERE, '..', 'upstream', 'srp', 'srp6_standard_groups.dart');
  const localCheckout = join(REPO, '.upstream', 'pub', 'lib', 'srp', 'srp6_standard_groups.dart');
  const src = readFileSync(existsSync(localCheckout) ? localCheckout : vendored, 'utf8');
  const lines = src.split(/\r?\n/);
  let collect = false;
  const parts = [];
  for (const l of lines) {
    if (l.includes('rfc5054_4096_N')) { collect = true; continue; }
    if (collect) {
      if (l.includes('rfc5054_4096_g')) break;
      const m = /'([0-9A-Fa-f]+)'/.exec(l);
      if (m) parts.push(m[1]);
    }
  }
  return parts.join('').toUpperCase();
}

const utf8 = (s) => new Uint8Array(new TextEncoder().encode(s));
const fromHex = (s) => new Uint8Array(Buffer.from(s, 'hex'));

const SRP_N_BYTES = 512;
const pad512 = (b) => {
  if (b.length >= SRP_N_BYTES) return b;
  const out = new Uint8Array(SRP_N_BYTES);
  out.set(b, SRP_N_BYTES - b.length);
  return out;
};
const bigToBytes = (v) => {
  let s = v.toString(16);
  if (s.length % 2) s = '0' + s;
  return fromHex(s);
};

// ---------------------------------------------------------------- the vector
const VECTOR = {
  srpUserID: 'repro-user-id',
  srpSalt: utf8('0123456789abcdef'),
  loginKey: utf8('1234567890abcdef'),
  aPrivate: fromHex(
    '0000000000000000000000000000000000000000000000000000000000000000' +
    '00000000000000000000000000000000000000000000000000000000000006de'),
  bPrivate: new Uint8Array(64).fill(0x42),
  expectedM1: 'c0953b8c74d400fbf664a515deb700d73b65231e7e207a2e2326ff8cf70567ac',
};

/** Reference implementation written directly from the upstream Dart sources. */
async function reference() {
  const N = Srp.N;
  const g = Srp.g;
  const sha256 = async (parts) => {
    const total = parts.reduce((n, p) => n + p.length, 0);
    const all = new Uint8Array(total);
    let o = 0;
    for (const p of parts) { all.set(p, o); o += p.length; }
    return new Uint8Array(await crypto.subtle.digest('SHA-256', all));
  };
  const decode = (bytes) => {
    let r = 0n;
    for (const b of bytes) r = (r << 8n) | BigInt(b);
    return r;
  };
  const encodeMinimal = (v) => {
    if (v === 0n) return new Uint8Array(0);
    let s = v.toString(16);
    if (s.length % 2) s = '0' + s;
    return fromHex(s);
  };
  const pad = (v, len) => {
    const b = encodeMinimal(v);
    if (b.length >= len) return b;
    const out = new Uint8Array(len);
    out.set(b, len - b.length);
    return out;
  };
  const modPow = (base, exp, mod) => {
    let r = 1n;
    let b = ((base % mod) + mod) % mod;
    let e = exp;
    while (e > 0n) {
      if (e & 1n) r = (r * b) % mod;
      b = (b * b) % mod;
      e >>= 1n;
    }
    return r;
  };

  // x = H(salt || H(identity || ':' || password))     (srp6_util.dart:19-33)
  const inner = await sha256([VECTOR.srpUserID === undefined ? new Uint8Array(0) : utf8(VECTOR.srpUserID),
    new Uint8Array([0x3a]), VECTOR.loginKey]);
  const x = decode(await sha256([VECTOR.srpSalt, inner]));

  // k = H(pad(N) || pad(g))                           (srp6_util.dart:11-13)
  const k = decode(await sha256([pad(N, 512), pad(g, 512)]));

  const a = decode(VECTOR.aPrivate);
  const A = modPow(g, a, N);
  const v = modPow(g, x, N);

  // Server side: B = (k*v + g^b) mod N
  const b = decode(VECTOR.bPrivate);
  const B = (k * v + modPow(g, b, N)) % N;

  // u = H(pad(A) || pad(B))                           (srp6_util.dart:15-17)
  const u = decode(await sha256([pad(A, 512), pad(B, 512)]));

  // S = (B - k*g^x)^(a + u*x) mod N                   (srp6_client.dart:49-55)
  const exp = u * x + a;
  const tmp = (modPow(g, x, N) * (k % N)) % N;
  const S = modPow(B - tmp, exp, N);

  // M1 = H(pad(A) || pad(B) || pad(S))                (srp6_util.dart:88-91)
  const M1 = await sha256([pad(A, 512), pad(B, 512), pad(S, 512)]);

  return { N, g, x, k, a, A, v, b, B, u, exp, S, M1 };
}

// ============================================================================

describe('SRP group parameters', () => {
  it('N is the RFC 5054 4096-bit modulus (read from the pinned upstream source)', () => {
    const expected = upstreamRfc5054_4096_N();
    assertEquals(expected.length, 1024, 'upstream N is 1024 hex chars');
    assertEquals(Srp.N.toString(16).toUpperCase(), expected, 'N must match rfc5054_4096_N');
    assertEquals(Srp.N.toString(2).length, 4096, 'N is 4096 bits');
    assertEquals(Srp.g, 5n, 'g = 5 (rfc5054_4096_g)');
  });

  it('padding length is 512 bytes for the 4096-bit group', () => {
    // (N.bitLength + 7) ~/ 8 == 512
    assertEquals(Math.ceil(Srp.N.toString(2).length / 8), 512, 'pad length');
  });
});

describe('SRP against the Go-server/Rust-client vector', () => {
  it('reference implementation reproduces the recorded M1', async () => {
    const r = await reference();
    assertEquals(hex(r.M1), VECTOR.expectedM1,
      'the from-spec reference must reproduce the Go server vector');
  });

  it('Srp.calculateX matches the reference', async () => {
    const ref = await reference();
    const x = await Srp.calculateX(VECTOR.srpSalt, utf8(VECTOR.srpUserID), VECTOR.loginKey);
    assertEquals(x.toString(16), ref.x.toString(16), 'x');
  });

  it('Srp.calculateK matches the reference', async () => {
    const ref = await reference();
    const k = await Srp.calculateK();
    assertEquals(k.toString(16), ref.k.toString(16), 'k');
  });

  it('Srp.generateVerifier matches the reference (g^x mod N)', async () => {
    const ref = await reference();
    const v = await Srp.generateVerifier(VECTOR.srpSalt, utf8(VECTOR.srpUserID), VECTOR.loginKey);
    assertEquals(v.toString(16), ref.v.toString(16), 'v');
  });

  it('Srp.modPow(A) and calculateU match the reference (leading-zero A edge case)', async () => {
    const ref = await reference();
    const A = Srp.modPow(Srp.g, ref.a, Srp.N);
    assertEquals(A.toString(16), ref.A.toString(16), 'A');
    // The vector's whole point: A is 511 bytes, so pad(A) must re-add the zero.
    assertEquals(bigToBytes(ref.A).length, SRP_N_BYTES - 1, 'A has a leading zero byte');
    assertEquals(Srp.getPadded(ref.A, 512).length, 512, 'padded A is 512 bytes');
    assertEquals(Srp.getPadded(ref.A, 512)[0], 0, 'pad byte is zero');

    const u = await Srp.calculateU(ref.A, ref.B);
    assertEquals(u.toString(16), ref.u.toString(16), 'u');
  });

  it('Srp.calculateSecret reproduces the Go server M1 end-to-end', async () => {
    const ref = await reference();
    const S = await Srp.calculateSecret(ref.B, ref.A, ref.a, ref.x);
    assertEquals(S.toString(16), ref.S.toString(16), 'S');
    const M1 = await Srp.calculateM1(ref.A, ref.B, S);
    assertEquals(hex(Srp.getPadded(M1, 32)), VECTOR.expectedM1,
      'M1 must equal the value the Go server produced');
  });

  it('Srp.getPadded(M1, 32) is the 32-byte digest (44 base64 chars, one "=")', async () => {
    const ref = await reference();
    const S = await Srp.calculateSecret(ref.B, ref.A, ref.a, ref.x);
    const M1 = await Srp.calculateM1(ref.A, ref.B, S);
    const padded = Srp.getPadded(M1, 32);
    assertEquals(padded.length, 32, 'M1 padded to 32');
    const b64 = CryptoUtil.bin2base64(padded);
    assertEquals(b64.length, 44, 'base64 length');
    assert(b64.endsWith('='), 'one padding char');
  });
});

describe('SRP wire encodings (the upstream asymmetry)', () => {
  it('srpA is base64 of the 512-byte padded value (684 chars, one "=")', async () => {
    const ref = await reference();
    const b64 = CryptoUtil.bin2base64(Srp.getPadded(ref.A, 512));
    assertEquals(b64.length, 684, '512 bytes -> 684 base64 chars');
    assert(b64.endsWith('='), 'one padding char');
  });

  it('srpVerifier is base64 of the MINIMAL big-endian value (NOT padded)', async () => {
    // upstream user_service.dart:660  base64Encode(SRP6Util.encodeBigInt(v))
    //                                   ^^^ no getPadded, unlike srpA on :661
    const ref = await reference();
    const minimal = Srp.encodeBigInt(ref.v);
    const padded = Srp.getPadded(ref.v, 512);
    assertEquals(Srp.decodeBigInt(minimal), ref.v, 'minimal bytes decode back to v');
    assertEquals(Srp.decodeBigInt(padded), ref.v, 'padded bytes decode back to v');
    assertEquals(minimal.length, 512, 'this particular v happens to be 512 bytes');
    // Use a value with a leading zero byte to show the two encodings diverge.
    const withLeadingZero = (1n << 4088n) + 12345n; // 512 bytes, top byte 0x01 -> still 512
    const short = 12345n;                            // 2 bytes
    assertEquals(Srp.encodeBigInt(short).length, 2, 'minimal encoding of 12345 is 2 bytes');
    assertEquals(Srp.getPadded(short, 512).length, 512, 'padded encoding is 512 bytes');
    assert(CryptoUtil.bin2base64(Srp.encodeBigInt(short)) !== CryptoUtil.bin2base64(Srp.getPadded(short, 512)),
      'minimal and padded base64 must differ');
    assertEquals(Srp.getPadded(short, 512)[0], 0, 'padded form is zero-filled on the left');
    void withLeadingZero;
  });

  it('encodeBigInt/decodeBigInt round-trip for edge values', () => {
    for (const v of [0n, 1n, 255n, 256n, 65535n, 65536n, (1n << 255n), (1n << 256n) - 1n]) {
      assertEquals(Srp.decodeBigInt(Srp.encodeBigInt(v)), v, `round trip ${v}`);
    }
    assertEquals(Srp.encodeBigInt(0n).length, 0, 'zero encodes to zero bytes (Dart bitLength 0)');
    assertEquals(Srp.encodeBigInt(1n).length, 1, 'one encodes to one byte');
    assertEquals(Srp.encodeBigInt(255n).length, 1, '255 encodes to one byte');
    assertEquals(Srp.encodeBigInt(256n).length, 2, '256 encodes to two bytes');
    assertEquals(Srp.bitLength(0n), 0, 'bitLength(0)');
    assertEquals(Srp.bitLength(1n), 1, 'bitLength(1)');
    assertEquals(Srp.bitLength(255n), 8, 'bitLength(255)');
    assertEquals(Srp.bitLength(256n), 9, 'bitLength(256)');
  });

  it('getPadded does not truncate values longer than the pad length', () => {
    const big = (1n << 4104n) - 1n; // 513 bytes
    const b = Srp.encodeBigInt(big);
    assertEquals(b.length, 513, 'value is 513 bytes');
    assertEquals(Srp.getPadded(big, 512).length, 513, 'no truncation');
  });
});

describe('SRP private value generation', () => {
  it('a is in [2^255, 2^256) and A = g^a mod N', async () => {
    const min = 1n << 255n;
    const max = 1n << 256n;
    for (let i = 0; i < 20; i++) {
      const creds = await Srp.generateCredentials(
        VECTOR.srpSalt, utf8(VECTOR.srpUserID), VECTOR.loginKey,
        () => new Uint8Array(crypto.getRandomValues(new Uint8Array(32))));
      assert(creds.a >= min && creds.a < max, `a out of range: ${creds.a.toString(16)}`);
      assertEquals(creds.A, Srp.modPow(Srp.g, creds.a, Srp.N), 'A = g^a mod N');
    }
  });

  it('a is rejected and redrawn when the first draw is below 2^255', async () => {
    let call = 0;
    const draws = [
      fromHex('0000000000000000000000000000000000000000000000000000000000000001'), // too small
      fromHex('8000000000000000000000000000000000000000000000000000000000000000'), // exactly 2^255
    ];
    const creds = await Srp.generateCredentials(
      VECTOR.srpSalt, utf8(VECTOR.srpUserID), VECTOR.loginKey,
      () => draws[call++]);
    assertEquals(call, 2, 'the small draw must be rejected');
    assertEquals(creds.a, 1n << 255n, 'second draw accepted');
  });
});

describe('SRP modPow correctness', () => {
  it('reduces a negative base into [0, N)', () => {
    // S = (B - k*g^x)^exp mod N; the base is negative roughly half the time.
    // Dart BigInt.modPow / Go big.Int.Exp / the Rust srp crate all reduce the
    // base modulo N first, so the port must too.
    const N = 1000003n;
    assertEquals(Srp.modPow(-1n, 2n, N), 1n, '(-1)^2 mod N');
    assertEquals(Srp.modPow(-1n, 3n, N), N - 1n, '(-1)^3 mod N');
    assertEquals(Srp.modPow(-5n, 1n, N), N - 5n, '(-5)^1 mod N');
    assertEquals(Srp.modPow(-5n, 3n, N), Srp.modPow(N - 5n, 3n, N), 'negative == reduced');
  });

  it('handles exponent 0 and 1', () => {
    assertEquals(Srp.modPow(12345n, 0n, 1000003n), 1n, 'x^0 = 1');
    assertEquals(Srp.modPow(12345n, 1n, 1000003n), 12345n, 'x^1 = x');
  });
});

describe('login key / identity inputs', () => {
  it('loginKey is exactly 16 bytes and identity is the srpUserID UTF-8 string', async () => {
    // The Rust client rejects any login key that is not 16 bytes
    // (srp.rs:34-39), which is the strongest available confirmation that the
    // 32->16 truncation in deriveLoginKey is load-bearing.
    const kek = fromHex('87b920448e0236d8a7e415fa3222e9fee9768292e6be6834d11616a6b0ea9323');
    const loginKey = await CryptoUtil.deriveLoginKey(kek);
    assertEquals(loginKey.length, 16, 'loginKey length');
    const identity = CryptoUtil.strToBin('repro-user-id');
    assertBytes(identity, utf8('repro-user-id'), 'identity is UTF-8 of the srpUserID');
  });

  it('a UUIDv4 srpUserID is 36 ASCII bytes', () => {
    const uuid = '123e4567-e89b-42d3-a456-426614174000';
    assertEquals(utf8(uuid).length, 36, 'UUID string length');
    assertEquals(CryptoUtil.strToBin(uuid).length, 36, 'port encodes it as 36 bytes');
  });
});
